this commit jump to addEventListener
Flaivers/Student-Manager pull request #4
Opened 2023-01-05 18:08 UTC by Flaivers

2023-01-05 18:19 UTC, 03leg requested changes

2023-01-05 18:19 UTC, 03leg commented on studentManager.js
> +  createButton () {
rename it and another, better name is `handleCreateStudentClick`

2023-01-05 18:20 UTC, 03leg commented on studentManager.js
> +  createButton () {
`handleDeleteStudentClick` and etc

2023-01-05 18:47 UTC, Flaivers commented on studentManager.js
> +  createButton () {
I changed the names

2023-01-09 15:11 UTC, 03leg approved these changes

2023-01-09 15:11 UTC, merged